
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/home/david/Desktop/Intel/Simics/simics-6.0.122
RAW_SIMICS_MODEL_BUILDER=/home/david/Desktop/Intel/Simics/simics-6.0.122
RAW_EML_PACKAGE=
RAW_DODOC_PKG=/home/david/Desktop/Intel/Simics/simics-6.0.122

RAW_SIMICS_PACKAGE_LIST=/home/david/Desktop/Intel/Simics/simics-6.0.122/.package-list

INCLUDE_PATHS = /home/david/Desktop/Intel/Simics/simics-6.0.122/src/include
CXX_INCLUDE_PATHS = /home/david/Desktop/Intel/Simics/simics-6.0.122/linux64/api
DML_INCLUDE_PATHS = /home/david/Desktop/Intel/Simics/simics-6.0.122/linux64/bin/dml/api
HOST_TYPE = linux64
