#!/bin/bash
# this file will be overwritten by the project setup script
SIMICS_BASE_PACKAGE="/home/david/Desktop/Intel/Simics/simics-6.0.122"
export SIMICS_BASE_PACKAGE
if [ -f "/home/david/Documents/repos/proyecto-ode/src/ODEcam/.package-list" ]; then
    exec "/home/david/Desktop/Intel/Simics/simics-6.0.122/bin/simics-eclipse" --package-list "/home/david/Documents/repos/proyecto-ode/src/ODEcam/.package-list" --project "/home/david/Documents/repos/proyecto-ode/src/ODEcam" "$@"
else
    exec "/home/david/Desktop/Intel/Simics/simics-6.0.122/bin/simics-eclipse" --project "/home/david/Documents/repos/proyecto-ode/src/ODEcam" "$@"
fi
