#                                                              -*- Makefile -*-
# Simics module makefile
#

SIMICS_API := 6
THREAD_SAFE:=yes
MODULE_CLASSES = sample_pci_device

SRC_FILES= sample-pci-device.dml
PYTHON_FILES := module_load.py

EXTRA_MODULE_VPATH += dml-lib

include $(MODULE_MAKEFILE)
